language: c
compiler:
    - gcc
before_install:
    - sudo apt-get install libcap2-bin
    - sudo apt-get install traceroute
    - traceroute google.com
install:
    -
script:
    - ci/build-2-install.sh
    - env PATH=`pwd`/src:$PATH prove ci/test-*.pl
    - ci/test-tarball.sh
