#!/usr/bin/perl -w

use strict;
use warnings;

use Test::More;
use t::common;

for my $arg (qw(i b B c C H i O p Q r t)) {
	subtest "testing usage on option $arg" => sub {
		my $cmd = t::Command->new(cmd => "$FPING -$arg xxx");
		$cmd->exit_is_num(1);
		$cmd->stdout_is_eq("");
		$cmd->stderr_like(qr{Usage:});
	};
}

done_testing;

# vi:syntax=perl
